# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu2404" do |cfg|
    cfg.vm.box = "gusztavvargadr/ubuntu-desktop-2404-lts"
    #cfg.vm.host_name = "pwn"
    
    name = "ubuntu2404"
    cpu = 2
    memory = 4096

    cfg.vm.provider "vmware_desktop" do |v|
      v.vmx["displayname"] = name
      v.cpus = cpu
      v.memory = memory
      v.gui = true
    end

    cfg.vm.provider "virtualbox" do |v|
      v.name = name
      v.cpus = cpu
      v.memory = memory
      #v.gui = true
    end
  
    cfg.vm.network "private_network", ip: "192.168.100.121"
    cfg.vm.network "forwarded_port", guest:22, host: 31337, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder ".", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "install_pkg.sh", privileged: false
  end
end
